version: '3'
services:
  lambda:
    build: .
    ports:
      - "9000:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - YOUTUBE_DATA_API_TOKEN=${YOUTUBE_DATA_API_TOKEN}